version: 2.1
orbs:
  android: circleci/android@1.0

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Javadoc
          command: make ci-javadoc
      - store_artifacts:
          path: ci/javadoc/build/reports
      - run:
          name: Build
          command: make ci-build
      - run:
          name: UnitTests
          command: make ci-unit-test
      - store_artifacts:
           path: ci/unit-test/build/reports
      - store_test_results:
           path: ci/unit-test/build/test-results
